export const eventNames = {
  CONNECT_WALLET_PROVIDER_RENDERED: 'CONNECT_WALLET_PROVIDER_RENDERED',
  CONNECT_WALLET_CONNECT_BUTTON_CLICKED:
    'CONNECT_WALLET_CONNECT_BUTTON_CLICKED',
  CONNECT_WALLET_CONNECTED_BUTTON_CLICKED:
    'CONNECT_WALLET_CONNECTED_BUTTON_CLICKED',
  CONNECT_WALLET_DISCONNECT_BUTTON_CLICKED:
    'CONNECT_WALLET_DISCONNECT_BUTTON_CLICKED',
  CONNECT_WALLET_CONNECTOR_BUTTON_CLICKED:
    'CONNECT_WALLET_CONNECTOR_BUTTON_CLICKED',
  CONNECT_WALLET_MODAL_BACK_BUTTON_CLICKED:
    'CONNECT_WALLET_MODAL_BACK_BUTTON_CLICKED',
  CONNECT_WALLET_MODAL_CLOSE_BUTTON_CLICKED:
    'CONNECT_WALLET_MODAL_CLOSE_BUTTON_CLICKED',
  CONNECT_WALLET_WHAT_IS_A_WALLET_BUTTON_CLICKED:
    'CONNECT_WALLET_WHAT_IS_A_WALLET_BUTTON_CLICKED',
  CONNECT_WALLET_RETRY_SIGNATURE_BUTTON_CLICKED:
    'CONNECT_WALLET_RETRY_SIGNATURE_BUTTON_CLICKED',
  CONNECT_WALLET_GET_WALLET_BUTTON_CLICKED:
    'CONNECT_WALLET_GET_WALLET_BUTTON_CLICKED',
  CONNECT_WALLET_USE_WALLET_BUTTON_CLICKED:
    'CONNECT_WALLET_USE_WALLET_BUTTON_CLICKED',
  CONNECT_WALLET_RETRY_CONNECTING_BUTTON_CLICKED:
    'CONNECT_WALLET_RETRY_CONNECTING_BUTTON_CLICKED',
  CONNECT_WALLET_USE_QR_CODE_BUTTON_CLICKED:
    'CONNECT_WALLET_USE_QR_CODE_BUTTON_CLICKED',
  CONNECT_WALLET_HELP_BUTTON_CLICKED: 'CONNECT_WALLET_HELP_BUTTON_CLICKED',
  CONNECT_WALLET_ON_CONNECT_EVENT: 'CONNECT_WALLET_ON_CONNECT_EVENT',
  CONNECT_WALLET_ON_SIGN_MESSAGE_EVENT: 'CONNECT_WALLET_ON_SIGN_MESSAGE_EVENT',
  CONNECT_WALLET_ON_DISCONNECT_EVENT: 'CONNECT_WALLET_ON_DISCONNECT_EVENT',
  TOKENGATE_COMPONENT_RENDERED: 'TOKENGATE_COMPONENT_RENDERED',
  TOKENGATE_ON_UNLOCK_EVENT: 'TOKENGATE_ON_UNLOCK_EVENT',
  TOKENGATE_ON_REQUIREMENTS_NOT_MET_EVENT:
    'TOKENGATE_ON_REQUIREMENTS_NOT_MET_EVENT',
  GATE_CONTEXT_CLIENT_ON_CONTEXT_SUBMITTED_TO_CART_ATTRIBUTES:
    'GATE_CONTEXT_CLIENT_ON_CONTEXT_SUBMITTED_TO_CART_ATTRIBUTES',
};
