name: Documentation Link
on:
  pull_request:
    types: [opened, ready_for_review]
    paths:
      - 'docusaurus/**'
    branches-ignore:
      - 'dependabot/**'

jobs:
  comment:
    name: Comment
    runs-on: shopify-ubuntu-latest
    permissions:
      pull-requests: write
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Branch to lower
        shell: bash
        run: echo "branch_lower=$(echo ${{ env.branch }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Sanitise branch name
        shell: bash
        run: echo "branch_sanitised=$(echo ${{ env.branch_lower }} | sed 's/[^A-Za-z0-9-]/-/g')" >> $GITHUB_ENV

      - name: Truncate branch
        shell: bash
        run: echo "branch_truncated=$(echo ${{ env.branch_sanitised }} | cut -c 1-30)" >> $GITHUB_ENV

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ':tophat: This PR can be tophatted on https://${{ github.event.repository.name }}--${{ env.branch_truncated }}.docs.shopify.io/ once the CI completes.'
          check_for_duplicate_msg: true
